import Head from 'next/head'
import Navbar from '../components/navbar'
import Collection from '../components/collection'
import AddButton from '../components/addButton'
import { useState,useEffect } from 'react'
import { getItems } from '../data/service'



export default function Home() {  
  const [collectionData, setCollectionData ] = useState([]);
  const [count, setCount] = useState(0)

  useEffect(()=>{
    console.log('Inside home useEffect')
    const items = getItems("collections")
   if (items) {setCollectionData(items)}
  },[count])
  
  return (
    <div className='min-h-screen  bg-gray-900 '>
     <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
    <Navbar> </Navbar>
    <div className='flex justify-center my-4 py-2'>
<AddButton count = {count} setCount = {setCount}/>

</div>
<section className='pb-10'>

<div className='container mx-auto mt-10'>
  {
    collectionData.map(
      (collection)=>(
          <Collection collectionData = {collection} key={collection._id} count2 = {count} setCount2 = {setCount}/>
      )
  )
  }
  </div>
</section>   



    </div>
  )
}
