import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/navbar'
import Sidebar from '../components/sidebar'
import Task from '../components/task'
import Collection from '../components/collection'
import AddButton from '../components/addButton'
import DatePicker from 'react-datepicker'
import { useState,useEffect } from 'react'



export default function Home() {  
  const [collectionData, setCollectionData ] = useState([]);
  useEffect(()=>{
    console.log('Inside home useEffect')
    const items = JSON.parse(window.localStorage.getItem("collections"))
   if (items) {setCollectionData(items)}
  },[])
  
  console.log(collectionData)
  return (
    <div className='h-full  bg-gray-900 '>
     <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
    <Navbar> </Navbar>
    <div className='flex justify-center my-4 py-2'>
<AddButton/>

</div>
<section className='pb-10'>

<div className='container mx-auto mt-10'>
  {
    collectionData.map(
      (collection)=>(
          <Collection collectionData = {collection} key={collection._id}/>
      )
  )
  }
  </div>
</section>   



    </div>
  )
}
